/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/dracula.theme.ts
 * Command: astryx theme build src/themes/dracula.theme.ts --out src/themes/dracula.css
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

/// <reference path="./dracula.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const draculaTheme: DefinedTheme;
